### ISSUE TITLE
Allure report is ugly

### ISSUE THREAD

**Issue by asolntsev** [allure-examples/allure-junit-example#11]
I have cloned your project, executed "mvn test site", and got an ugly report.

![image](https://cloud.githubusercontent.com/assets/279773/6282478/a848a6f4-b8de-11e4-8b61-55b57b6c36f7.png)

**Comment by clicman** [comment]
It doesn`t work on local filesystem. Try to open it under http context. Or just use allure-cli to open it.

**Comment by just-boris** [comment]
@clicman is right. Allure has too smart fronted to open just a simple file.

But earlier there was a better message about it.

**Comment by just-boris** [comment]
Add link to FAQ, where it is described in https://github.com/allure-framework/allure-core/issues/493

**Comment by asolntsev** [comment]
I suggest you to add `jetty-maven-plugin` to the project, so that it would be easy to users to run it with maven. 

Take a look at this tutorial: http://artkoshelev.github.io/posts/hello-allure/

**Comment by vania-pooh** [comment]
@asolntsev our CLI has ```$ allure report open``` command which starts Jetty on random free port.

**Comment by asolntsev** [comment]
@vania-pooh Good to know, but it's too complex for newbie user. Then he needs to research what is "cli", how to install it, etc. You already have maven in the project. The minimalistic option is just to run `mvn jetty:run` without installing anything else.

**Comment by vania-pooh** [comment]
@baev thoughts?

**Comment by just-boris** [comment]
In my opinion it's bad idea to pollute your project unrequired dependencies.
If you need external tools for development – use it, but there is no need to keep it in project scope

**Comment by clicman** [comment]
I think @asolntsev right in case to add jetty to example project. It will not overload adaptor, but will provide working report after goal execution.

**Comment by vania-pooh** [comment]
@asolntsev, @clicman : your pull requests to examples are welcome. :)

**Comment by asolntsev** [comment]
@vania-pooh @clicman Submitted pull request: https://github.com/allure-examples/allure-junit-example/pull/12
